name: lando-wp-experiments
recipe: wordpress

config:
    webroot: web
    php: 8.1

env_file:
    - .env


services:
    appserver:
        run:
            - composer install

    node:
        type: node:18
        command: yarn run dev
        run:
            - yarn install
proxy:
    node:
        - bud.lando-wp-experiments.lndo.site:3000
